version: '3.8'

services:
  python:
    build: ./python
    volumes:
      - ./python:/app

  javascript:
    build: ./javascript
    volumes:
      - ./javascript:/app

  java:
    build: ./java
    volumes:
      - ./java:/app

  c:
    build: ./c
    volumes:
      - ./c:/app

  cpp:
    build: ./cpp
    volumes:
      - ./cpp:/app

  collector:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "resulting_code.py"]
    depends_on:
      - python
      - javascript
      - java
      - c
      - cpp
